### ISSUE TITLE
feat: Handy Iconography 적용

### ISSUE THREAD

**Issue by nijuy** [yourssu/YDS-React#120]
# ISSUE ✅ : Handy Iconography 적용

## 📖 Summary

이번 Handy에서 제안된 내용대로 아이콘 컴포넌트를 수정합니다

## Todo
- [x] Figma svg export
- [x] svg 파일명 수정
- [x] 기존 파일 삭제
  - [x] `iconAsset/*`
  - [x] `component/*` (except `YDSWrapper` - 기존 아이콘을 쓰는 컴포넌트들이 있어서)
  - [x] `icons/generated/*`
  - [x] `IconContext.Provider`
- [x] `IconProps` 타입 수정
  - [x] 아이콘 크기 제한 (7종류)
  - [x] `mirrored` 필드 삭제
- [x] `convert-icon`
- [x] 검토
- [x] 문서 수정
